import LegalLayout from "@/components/layouts/LegalLayout";

export default function Disclaimers() {
  return (
    <>
      <h2 className="text-3xl font-bold mt-2 mb-4">Disclaimers</h2>
      
      <h2>1. General Disclaimer</h2>
      <p>THE VICTURE HEALTHCARE SOLUTIONS SOFTWARE AND SERVICES ("SERVICE") IS PROVIDED "AS IS" AND "AS AVAILABLE," WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED.</p>
      
      <h2>2. Disclaimer of Warranties</h2>
      <p>VICTURE HEALTHCARE SOLUTIONS ("VICTURE") EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WITHOUT LIMITING THE FOREGOING, VICTURE DOES NOT WARRANT THAT:</p>
      <ul>
        <li>THE SERVICE WILL MEET YOUR SPECIFIC REQUIREMENTS</li>
        <li>THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE</li>
        <li>THE RESULTS OBTAINED FROM THE USE OF THE SERVICE WILL BE ACCURATE OR RELIABLE</li>
        <li>THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICE WILL MEET YOUR EXPECTATIONS</li>
        <li>ANY ERRORS IN THE SERVICE WILL BE CORRECTED</li>
      </ul>
      
      <h2>3. Medical Disclaimer</h2>
      <p>THE SERVICE IS NOT A SUBSTITUTE FOR PROFESSIONAL MEDICAL ADVICE, DIAGNOSIS, OR TREATMENT. THE SERVICE IS DESIGNED TO ASSIST WITH PHARMACY MANAGEMENT, BUT SHOULD NOT BE USED TO MAKE MEDICAL DECISIONS WITHOUT APPROPRIATE PROFESSIONAL JUDGMENT.</p>
      <p>RELIANCE ON ANY INFORMATION PROVIDED BY THE SERVICE IS SOLELY AT YOUR OWN RISK. VICTURE IS NOT RESPONSIBLE OR LIABLE FOR ANY ADVICE, COURSE OF TREATMENT, DIAGNOSIS, OR ANY OTHER INFORMATION, SERVICES, OR PRODUCTS THAT YOU OBTAIN THROUGH THE SERVICE.</p>
      
      <h2>4. Pharmacy Compliance Disclaimer</h2>
      <p>THE SERVICE IS DESIGNED TO ASSIST WITH PHARMACY MANAGEMENT OPERATIONS, BUT IT IS YOUR RESPONSIBILITY TO ENSURE COMPLIANCE WITH ALL APPLICABLE LAWS, REGULATIONS, AND PROFESSIONAL STANDARDS RELATED TO PHARMACY OPERATIONS.</p>
      <p>VICTURE DOES NOT GUARANTEE THAT USE OF THE SERVICE WILL ENSURE COMPLIANCE WITH REGULATORY REQUIREMENTS. YOU ARE SOLELY RESPONSIBLE FOR ENSURING THAT YOUR USE OF THE SERVICE AND YOUR PHARMACY OPERATIONS COMPLY WITH ALL APPLICABLE LAWS AND REGULATIONS.</p>
      
      <h2>5. Data and Security Disclaimer</h2>
      <p>WHILE VICTURE IMPLEMENTS REASONABLE SECURITY MEASURES TO PROTECT YOUR DATA, NO METHOD OF TRANSMISSION OVER THE INTERNET OR ELECTRONIC STORAGE IS 100% SECURE. VICTURE CANNOT GUARANTEE THE ABSOLUTE SECURITY OF YOUR DATA.</p>
      <p>YOU ARE RESPONSIBLE FOR MAINTAINING THE SECURITY AND CONFIDENTIALITY OF YOUR ACCOUNT CREDENTIALS AND FOR ALL ACTIVITIES THAT OCCUR UNDER YOUR ACCOUNT.</p>
      
      <h2>6. Limitation of Liability</h2>
      <p>IN NO EVENT SHALL VICTURE BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM:</p>
      <ul>
        <li>YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICE</li>
        <li>ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE SERVICE</li>
        <li>ANY CONTENT OBTAINED FROM THE SERVICE</li>
        <li>UNAUTHORIZED ACCESS, USE, OR ALTERATION OF YOUR TRANSMISSIONS OR CONTENT</li>
      </ul>
      
      <h2>7. Contact Information</h2>
      <p>If you have any questions about these disclaimers, please contact us at victurehealthcaresolutions@gmail.com.</p>
      
      <p>Last Updated: {new Date().toLocaleDateString()}</p>
    </>
  );
}
