
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aysdilfgxlyuplikmmdt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5c2RpbGZneGx5dXBsaWttbWR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxNjU0NTAsImV4cCI6MjA1NTc0MTQ1MH0.7OLDoAC5i8F6IbORW7kY6at5pWdTZDB44D0g6kPaWpA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    storage: localStorage
  },
  global: {
    headers: {
      'X-Client-Info': 'victure-pharmacy-web',
    },
  },
  // Safer defaults for fetch
  fetch: (url, options) => {
    const updatedOptions = {
      ...options,
      credentials: 'same-origin', // Include cookies for same-origin requests
      cache: 'no-store', // Prevent caching of sensitive data
      headers: {
        ...options?.headers,
        'X-Requested-With': 'XMLHttpRequest', // helps prevent CSRF
      }
    };
    return fetch(url, updatedOptions);
  }
});

// Export security-enhanced version of auth state change
export const onAuthStateChange = (callback: (session: any) => void) => {
  const { data } = supabase.auth.onAuthStateChange((event, session) => {
    if (event === 'SIGNED_IN' || event === 'TOKEN_REFRESHED') {
      console.log('User authenticated with secure session');
    }
    callback(session);
  });
  
  return data;
};
