
import { format } from "date-fns";

export function createInventoryReport(container: HTMLElement, data: any[]) {
  const table = document.createElement('table');
  table.style.width = '100%';
  table.style.borderCollapse = 'collapse';
  
  // Table header
  const thead = document.createElement('thead');
  thead.innerHTML = `
    <tr>
      <th style="border: 1px solid #ddd; padding: 8px; text-align: left; background-color: #f2f2f2;">Name</th>
      <th style="border: 1px solid #ddd; padding: 8px; text-align: left; background-color: #f2f2f2;">Quantity</th>
      <th style="border: 1px solid #ddd; padding: 8px; text-align: left; background-color: #f2f2f2;">Unit Cost</th>
      <th style="border: 1px solid #ddd; padding: 8px; text-align: left; background-color: #f2f2f2;">Total Value</th>
      <th style="border: 1px solid #ddd; padding: 8px; text-align: left; background-color: #f2f2f2;">Status</th>
    </tr>
  `;
  table.appendChild(thead);
  
  // Table body
  const tbody = document.createElement('tbody');
  let totalValue = 0;
  
  data.forEach((item, index) => {
    const row = document.createElement('tr');
    const itemValue = (item.quantity || 0) * (item.unit_cost || 0);
    totalValue += itemValue;
    
    row.style.backgroundColor = index % 2 === 0 ? '#f9f9f9' : 'white';
    
    row.innerHTML = `
      <td style="border: 1px solid #ddd; padding: 8px;">${item.name}</td>
      <td style="border: 1px solid #ddd; padding: 8px;">${item.quantity || 0}</td>
      <td style="border: 1px solid #ddd; padding: 8px;">₹${(item.unit_cost || 0).toFixed(2)}</td>
      <td style="border: 1px solid #ddd; padding: 8px;">₹${itemValue.toFixed(2)}</td>
      <td style="border: 1px solid #ddd; padding: 8px;">${item.status || 'N/A'}</td>
    `;
    
    tbody.appendChild(row);
  });
  
  table.appendChild(tbody);
  
  // Summary
  const summary = document.createElement('div');
  summary.style.marginTop = '20px';
  summary.innerHTML = `
    <p><strong>Total Items:</strong> ${data.length}</p>
    <p><strong>Total Inventory Value:</strong> ₹${totalValue.toFixed(2)}</p>
    <p><strong>Report Generated:</strong> ${format(new Date(), 'PPpp')}</p>
  `;
  
  container.appendChild(table);
  container.appendChild(summary);
}

export function createSalesReport(container: HTMLElement, data: any[]) {
  // Add a heading for the sales report section
  const reportHeading = document.createElement('div');
  reportHeading.style.marginBottom = '20px';
  reportHeading.style.padding = '15px';
  reportHeading.style.backgroundColor = '#f8f9fa';
  reportHeading.style.borderRadius = '5px';
  reportHeading.style.border = '1px solid #e9ecef';
  
  reportHeading.innerHTML = `
    <h2 style="margin: 0; color: #003366; font-size: 18px;">Sales Transaction Report</h2>
    <p style="margin: 5px 0 0; color: #6c757d;">Generated by Victure Healthcare Solutions</p>
  `;
  
  container.appendChild(reportHeading);

  // Transaction summary section
  const summarySection = document.createElement('div');
  summarySection.style.display = 'flex';
  summarySection.style.justifyContent = 'space-between';
  summarySection.style.marginBottom = '20px';
  summarySection.style.flexWrap = 'wrap';
  
  // Calculate summary data
  let totalSales = 0;
  let avgTransaction = 0;
  let highestBill = 0;
  
  data.forEach(bill => {
    const amount = bill.total_amount || 0;
    totalSales += amount;
    highestBill = Math.max(highestBill, amount);
  });
  
  avgTransaction = data.length > 0 ? totalSales / data.length : 0;
  
  // Create summary cards
  const createSummaryCard = (title, value, icon) => {
    const card = document.createElement('div');
    card.style.flex = '1';
    card.style.minWidth = '200px';
    card.style.padding = '15px';
    card.style.margin = '0 10px 10px 0';
    card.style.backgroundColor = '#ffffff';
    card.style.borderRadius = '5px';
    card.style.boxShadow = '0 2px 4px rgba(0,0,0,0.05)';
    card.style.border = '1px solid #e0e0e0';
    
    card.innerHTML = `
      <div style="font-size: 14px; color: #6c757d; margin-bottom: 5px;">${title}</div>
      <div style="font-size: 20px; font-weight: bold; color: #003366;">${value}</div>
      <div style="color: #6c757d; font-size: 20px; text-align: right;">${icon}</div>
    `;
    
    return card;
  };
  
  summarySection.appendChild(createSummaryCard('Total Sales', `₹${totalSales.toFixed(2)}`, '💰'));
  summarySection.appendChild(createSummaryCard('Number of Transactions', data.length, '🧾'));
  summarySection.appendChild(createSummaryCard('Avg. Transaction', `₹${avgTransaction.toFixed(2)}`, '📊'));
  summarySection.appendChild(createSummaryCard('Highest Bill', `₹${highestBill.toFixed(2)}`, '🔝'));
  
  container.appendChild(summarySection);

  // Transaction table
  const table = document.createElement('table');
  table.style.width = '100%';
  table.style.borderCollapse = 'collapse';
  table.style.marginTop = '15px';
  
  // Table header
  const thead = document.createElement('thead');
  thead.innerHTML = `
    <tr>
      <th style="border: 1px solid #ddd; padding: 10px; text-align: left; background-color: #003366; color: white;">Bill #</th>
      <th style="border: 1px solid #ddd; padding: 10px; text-align: left; background-color: #003366; color: white;">Date</th>
      <th style="border: 1px solid #ddd; padding: 10px; text-align: left; background-color: #003366; color: white;">Items</th>
      <th style="border: 1px solid #ddd; padding: 10px; text-align: left; background-color: #003366; color: white;">Amount</th>
      <th style="border: 1px solid #ddd; padding: 10px; text-align: left; background-color: #003366; color: white;">Status</th>
    </tr>
  `;
  table.appendChild(thead);
  
  // Table body
  const tbody = document.createElement('tbody');
  
  data.forEach((bill, index) => {
    const row = document.createElement('tr');
    row.style.backgroundColor = index % 2 === 0 ? '#f9f9f9' : 'white';
    
    const billDate = bill.date ? format(new Date(bill.date), 'yyyy-MM-dd') : 'N/A';
    const itemCount = bill.bill_items?.length || 0;
    
    row.innerHTML = `
      <td style="border: 1px solid #ddd; padding: 8px;">${bill.bill_number}</td>
      <td style="border: 1px solid #ddd; padding: 8px;">${billDate}</td>
      <td style="border: 1px solid #ddd; padding: 8px;">${itemCount}</td>
      <td style="border: 1px solid #ddd; padding: 8px;">₹${(bill.total_amount || 0).toFixed(2)}</td>
      <td style="border: 1px solid #ddd; padding: 8px;">
        <span style="
          display: inline-block;
          padding: 3px 8px;
          border-radius: 12px;
          font-size: 12px;
          background-color: ${bill.status === 'Completed' ? '#d4edda' : '#f8d7da'};
          color: ${bill.status === 'Completed' ? '#155724' : '#721c24'};
        ">
          ${bill.status || 'N/A'}
        </span>
      </td>
    `;
    
    tbody.appendChild(row);
  });
  
  table.appendChild(tbody);
  container.appendChild(table);
  
  // Footer with report metadata
  const footer = document.createElement('div');
  footer.style.marginTop = '30px';
  footer.style.paddingTop = '10px';
  footer.style.borderTop = '1px solid #dee2e6';
  footer.style.fontSize = '12px';
  footer.style.color = '#6c757d';
  footer.style.textAlign = 'center';
  
  footer.innerHTML = `
    <p>Report generated on ${format(new Date(), 'PPpp')} by Victure Healthcare Solutions</p>
    <p style="margin-top: 5px;">This report contains all sales transactions in your system. For financial purposes only.</p>
  `;
  
  container.appendChild(footer);
}

export function createPurchaseOrdersReport(container: HTMLElement, data: any[]) {
  const table = document.createElement('table');
  table.style.width = '100%';
  table.style.borderCollapse = 'collapse';
  
  // Table header
  const thead = document.createElement('thead');
  thead.innerHTML = `
    <tr>
      <th style="border: 1px solid #ddd; padding: 8px; text-align: left; background-color: #f2f2f2;">PO #</th>
      <th style="border: 1px solid #ddd; padding: 8px; text-align: left; background-color: #f2f2f2;">Supplier</th>
      <th style="border: 1px solid #ddd; padding: 8px; text-align: left; background-color: #f2f2f2;">Order Date</th>
      <th style="border: 1px solid #ddd; padding: 8px; text-align: left; background-color: #f2f2f2;">Items</th>
      <th style="border: 1px solid #ddd; padding: 8px; text-align: left; background-color: #f2f2f2;">Amount</th>
      <th style="border: 1px solid #ddd; padding: 8px; text-align: left; background-color: #f2f2f2;">Status</th>
    </tr>
  `;
  table.appendChild(thead);
  
  // Table body
  const tbody = document.createElement('tbody');
  let totalAmount = 0;
  
  data.forEach((order, index) => {
    const row = document.createElement('tr');
    totalAmount += (order.total_amount || 0);
    
    row.style.backgroundColor = index % 2 === 0 ? '#f9f9f9' : 'white';
    
    const orderDate = order.order_date ? format(new Date(order.order_date), 'yyyy-MM-dd') : 'N/A';
    const itemCount = order.purchase_order_items?.length || 0;
    
    row.innerHTML = `
      <td style="border: 1px solid #ddd; padding: 8px;">PO-${order.id}</td>
      <td style="border: 1px solid #ddd; padding: 8px;">${order.supplier_name}</td>
      <td style="border: 1px solid #ddd; padding: 8px;">${orderDate}</td>
      <td style="border: 1px solid #ddd; padding: 8px;">${itemCount}</td>
      <td style="border: 1px solid #ddd; padding: 8px;">₹${(order.total_amount || 0).toFixed(2)}</td>
      <td style="border: 1px solid #ddd; padding: 8px;">${order.status}</td>
    `;
    
    tbody.appendChild(row);
  });
  
  table.appendChild(tbody);
  
  // Summary
  const summary = document.createElement('div');
  summary.style.marginTop = '20px';
  summary.innerHTML = `
    <p><strong>Total Purchase Orders:</strong> ${data.length}</p>
    <p><strong>Total Order Value:</strong> ₹${totalAmount.toFixed(2)}</p>
    <p><strong>Report Generated:</strong> ${format(new Date(), 'PPpp')}</p>
  `;
  
  container.appendChild(table);
  container.appendChild(summary);
}

export function createPatientsReport(container: HTMLElement, data: any[]) {
  const table = document.createElement('table');
  table.style.width = '100%';
  table.style.borderCollapse = 'collapse';
  
  // Table header
  const thead = document.createElement('thead');
  thead.innerHTML = `
    <tr>
      <th style="border: 1px solid #ddd; padding: 8px; text-align: left; background-color: #f2f2f2;">Patient ID</th>
      <th style="border: 1px solid #ddd; padding: 8px; text-align: left; background-color: #f2f2f2;">Name</th>
      <th style="border: 1px solid #ddd; padding: 8px; text-align: left; background-color: #f2f2f2;">Phone Number</th>
      <th style="border: 1px solid #ddd; padding: 8px; text-align: left; background-color: #f2f2f2;">Status</th>
      <th style="border: 1px solid #ddd; padding: 8px; text-align: left; background-color: #f2f2f2;">Added On</th>
    </tr>
  `;
  table.appendChild(thead);
  
  // Table body
  const tbody = document.createElement('tbody');
  
  data.forEach((patient, index) => {
    const row = document.createElement('tr');
    row.style.backgroundColor = index % 2 === 0 ? '#f9f9f9' : 'white';
    
    const createdDate = patient.created_at ? format(new Date(patient.created_at), 'yyyy-MM-dd') : 'N/A';
    
    row.innerHTML = `
      <td style="border: 1px solid #ddd; padding: 8px;">${patient.id}</td>
      <td style="border: 1px solid #ddd; padding: 8px;">${patient.name}</td>
      <td style="border: 1px solid #ddd; padding: 8px;">${patient.phone_number}</td>
      <td style="border: 1px solid #ddd; padding: 8px;">${patient.status || 'Active'}</td>
      <td style="border: 1px solid #ddd; padding: 8px;">${createdDate}</td>
    `;
    
    tbody.appendChild(row);
  });
  
  table.appendChild(tbody);
  
  // Summary
  const summary = document.createElement('div');
  summary.style.marginTop = '20px';
  summary.innerHTML = `
    <p><strong>Total Patients:</strong> ${data.length}</p>
    <p><strong>Report Generated:</strong> ${format(new Date(), 'PPpp')}</p>
  `;
  
  container.appendChild(table);
  container.appendChild(summary);
}
